#!/bin/bash

# Based on https://github.com/aglitke/oc-kubevirt-up

VERBOSE=false
DATA_DIR="$PWD/_data"
CMD=$0

exec 3>&1
info() { echo -e "INFO $@" >&3 ; }
call() { $VERBOSE && echo -e "$ $@" >&3 ; eval "$@" ; }

#
# Clean
#
if [[ "$1" == "clean" ]]; then
  oc cluster down
  call sudo rm -rf $DATA_DIR /var/lib/origin/openshift.local.config/  /var/lib/origin/openshift.local.pv /var/lib/origin/openshift.local.volumes
  info "Some errors are okay."
  exit 0
fi

[[ "$@" =~ -v ]] && VERBOSE=true


#
# Setup
#
set -e

if [[ "$(oc get crd 2>/dev/null)" =~ .*kubevirt.* ]];
then
  info "It looks like the CNV demo is already deployed. Aborting."
  info "If you want to start fresh, run: $CMD clean"
  exit 1
fi

info "Setting up the CNV Demo (this can take a few minutes)"
mkdir -p $DATA_DIR

{
  set -ex
  if oc cluster status ; then
    info "Reusing the existing 'oc cluster' setup"
    info "NOTE: It is more likely that CNV will fail to work on a pre-configured 'oc cluster' setup"
  else
    info "Setting up 'oc cluster'"
    call oc cluster up --service-catalog --host-data-dir=$DATA_DIR --use-existing-config=true --skip-registry-check
    info "Waiting for OpenShift to be fully up"
    {
     N=60
     while [[ "$N" -gt 0 ]] ;
     do
       oc cluster status && break
       sleep 1
       N=$(( $N - 1 ))
     done
    } > /dev/null 2>&1
  fi
  
  call oc login -u system:admin
  
  #
  # Kubevirt
  #
  info "Deploying KubeVirt"
  call oc adm policy add-scc-to-user privileged -z kubevirt-privileged -n kube-system
  call oc adm policy add-scc-to-user privileged -z kubevirt-controller -n kube-system
  call oc adm policy add-scc-to-user privileged -z kubevirt-infra -n kube-system
  call oc apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.4.1/kubevirt.yaml
  
  info "Deploying examples"
  call oc apply -f vm.yaml
  
  #
  # Allow developer and TSB to do everything
  #
  info "Granting additional permissions"
  call oc adm policy add-cluster-role-to-user cluster-admin developer
  call oc adm policy add-cluster-role-to-user cluster-admin system:service-account:openshift-infra:template-instance-controller
  
  #
  # Use the image with KubeVirt additions
  #
  info "Switching to the OpenShift Web Console demo image"
  call oc set image -n openshift-web-console deployment webconsole webconsole=mutism/origin-web-console:demo
  set +x
} > .logs 2>&1

#
# Do output to point the user to the right URL
#
info "Done, connection details:"
echo ""
{
  oc login -u developer
  grep -A 10 started .logs
} | sed -e "s/^/> /"
echo ""
info "For CNV: Log into the web console as 'developer' and go to https://127.0.0.1:8443/console/project/myproject/overview"
